# Your make file is WRONG. how can you say that 1.4 is created when you still
# have to create it? The same for "deleted"
# Also, it's missing a space between ':' and '1.4.c'

all:1.4.c
	@echo 1.4 created
	@gcc -o 1.4 1.4.c -Wall -Wextra
clean:
	@echo 1.4 Deleted :P
	@rm 1.4

